import type { AIModel, Category } from "./types";

// Sidebar navigation categories (matches the Pencil design)
export const CATEGORIES: Category[] = [
  { slug: "ai-ml", name: "AI / ML", icon: "brain" },
  { slug: "chatgpt", name: "ChatGPT", icon: "monitor" },
  { slug: "claude", name: "Claude", icon: "sparkles" },
  { slug: "gemini", name: "Gemini", icon: "gem" },
  { slug: "global-news", name: "Global News", icon: "globe" },
];

// Top-level navigation links (Header)
export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/trending", label: "Trending" },
  { href: "/saved", label: "Saved" },
  { href: "/newsletter", label: "Newsletter" },
] as const;

// 24 AI Models data for the AI Models grid
export const AI_MODELS: AIModel[] = [
  // --- LLM ---
  {
    slug: "chatgpt",
    name: "ChatGPT",
    company: "OpenAI",
    description: "Conversational AI assistant with GPT-5 Turbo",
    color: "#10A37F",
    colorSecondary: "#1A7F5A",
    category: "llm",
    websiteUrl: "https://chat.openai.com",
    blogUrl: "https://openai.com/blog",
  },
  {
    slug: "claude",
    name: "Claude",
    company: "Anthropic",
    description: "AI assistant focused on safety and helpfulness",
    color: "#D4A574",
    colorSecondary: "#8B6914",
    category: "llm",
    websiteUrl: "https://claude.ai",
    blogUrl: "https://www.anthropic.com/blog",
  },
  {
    slug: "gemini",
    name: "Gemini",
    company: "Google",
    description: "Multimodal AI model by Google DeepMind",
    color: "#4285F4",
    colorSecondary: "#1A73E8",
    category: "multimodal",
    websiteUrl: "https://gemini.google.com",
    blogUrl: "https://blog.google/technology/ai/",
  },
  {
    slug: "grok",
    name: "Grok",
    company: "xAI",
    description: "AI assistant with real-time X integration",
    color: "#1DA1F2",
    colorSecondary: "#0D8BD9",
    category: "llm",
    websiteUrl: "https://grok.x.ai",
    blogUrl: null,
  },
  {
    slug: "copilot",
    name: "Copilot",
    company: "Microsoft",
    description: "AI-powered assistant integrated across Microsoft products",
    color: "#7B68EE",
    colorSecondary: "#5A4FCF",
    category: "llm",
    websiteUrl: "https://copilot.microsoft.com",
    blogUrl: null,
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    company: "Perplexity AI",
    description: "AI-powered search engine with citations",
    color: "#20B2AA",
    colorSecondary: "#1A8F88",
    category: "search",
    websiteUrl: "https://perplexity.ai",
    blogUrl: "https://blog.perplexity.ai",
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    company: "DeepSeek",
    description: "Open-source LLM with strong reasoning capabilities",
    color: "#4169E1",
    colorSecondary: "#2850C8",
    category: "open-source",
    websiteUrl: "https://deepseek.com",
    blogUrl: null,
  },
  {
    slug: "mistral",
    name: "Mistral",
    company: "Mistral AI",
    description: "European open-source AI model leader",
    color: "#FF6B35",
    colorSecondary: "#E55A2B",
    category: "open-source",
    websiteUrl: "https://mistral.ai",
    blogUrl: "https://mistral.ai/news",
  },
  {
    slug: "meta-ai",
    name: "Meta AI",
    company: "Meta",
    description: "Llama-based AI models and Meta AI assistant",
    color: "#0668E1",
    colorSecondary: "#0550B5",
    category: "open-source",
    websiteUrl: "https://ai.meta.com",
    blogUrl: "https://ai.meta.com/blog/",
  },
  // --- Image Generation ---
  {
    slug: "midjourney",
    name: "Midjourney",
    company: "Midjourney",
    description: "AI image generation with artistic quality",
    color: "#E8E8E8",
    colorSecondary: "#B0B0B0",
    category: "image",
    websiteUrl: "https://midjourney.com",
    blogUrl: null,
  },
  {
    slug: "dall-e",
    name: "DALL-E",
    company: "OpenAI",
    description: "Text-to-image AI model by OpenAI",
    color: "#FF6F61",
    colorSecondary: "#E85A4F",
    category: "image",
    websiteUrl: "https://openai.com/dall-e-3",
    blogUrl: null,
  },
  {
    slug: "stable-diffusion",
    name: "Stable Diffusion",
    company: "Stability AI",
    description: "Open-source image generation model",
    color: "#A855F7",
    colorSecondary: "#9333EA",
    category: "image",
    websiteUrl: "https://stability.ai",
    blogUrl: "https://stability.ai/blog",
  },
  {
    slug: "flux",
    name: "Flux",
    company: "Black Forest Labs",
    description: "Next-gen image model from ex-Stability AI team",
    color: "#F59E0B",
    colorSecondary: "#D97706",
    category: "image",
    websiteUrl: "https://blackforestlabs.ai",
    blogUrl: null,
  },
  // --- Video / Audio ---
  {
    slug: "suno",
    name: "Suno",
    company: "Suno AI",
    description: "AI music generation from text prompts",
    color: "#EC4899",
    colorSecondary: "#DB2777",
    category: "multimodal",
    websiteUrl: "https://suno.ai",
    blogUrl: null,
  },
  {
    slug: "runway",
    name: "Runway",
    company: "Runway",
    description: "AI video generation and editing suite",
    color: "#06B6D4",
    colorSecondary: "#0891B2",
    category: "multimodal",
    websiteUrl: "https://runwayml.com",
    blogUrl: "https://runwayml.com/blog",
  },
  {
    slug: "pika",
    name: "Pika",
    company: "Pika Labs",
    description: "AI video creation made accessible",
    color: "#8B5CF6",
    colorSecondary: "#7C3AED",
    category: "multimodal",
    websiteUrl: "https://pika.art",
    blogUrl: null,
  },
  // --- Code ---
  {
    slug: "cursor",
    name: "Cursor",
    company: "Anysphere",
    description: "AI-first code editor built on VS Code",
    color: "#6366F1",
    colorSecondary: "#4F46E5",
    category: "code",
    websiteUrl: "https://cursor.com",
    blogUrl: "https://cursor.com/blog",
  },
  {
    slug: "devin",
    name: "Devin",
    company: "Cognition",
    description: "First autonomous AI software engineer",
    color: "#14B8A6",
    colorSecondary: "#0D9488",
    category: "code",
    websiteUrl: "https://devin.ai",
    blogUrl: null,
  },
  {
    slug: "replit",
    name: "Replit",
    company: "Replit",
    description: "AI-powered collaborative coding platform",
    color: "#F26522",
    colorSecondary: "#D4561D",
    category: "code",
    websiteUrl: "https://replit.com",
    blogUrl: "https://blog.replit.com",
  },
  {
    slug: "v0",
    name: "v0",
    company: "Vercel",
    description: "AI-powered UI component generator",
    color: "#FFFFFF",
    colorSecondary: "#A0A0A0",
    category: "code",
    websiteUrl: "https://v0.dev",
    blogUrl: null,
  },
  {
    slug: "bolt",
    name: "Bolt",
    company: "StackBlitz",
    description: "AI full-stack web app builder in the browser",
    color: "#F97316",
    colorSecondary: "#EA580C",
    category: "code",
    websiteUrl: "https://bolt.new",
    blogUrl: null,
  },
  {
    slug: "lovable",
    name: "Lovable",
    company: "Lovable",
    description: "AI-powered app builder for non-developers",
    color: "#E11D48",
    colorSecondary: "#BE123C",
    category: "code",
    websiteUrl: "https://lovable.dev",
    blogUrl: null,
  },
  {
    slug: "windsurf",
    name: "Windsurf",
    company: "Codeium",
    description: "AI-powered IDE with deep codebase understanding",
    color: "#22D3EE",
    colorSecondary: "#06B6D4",
    category: "code",
    websiteUrl: "https://windsurf.com",
    blogUrl: null,
  },
  // --- Other ---
  {
    slug: "notebooklm",
    name: "NotebookLM",
    company: "Google",
    description: "AI research assistant for documents and notes",
    color: "#FACC15",
    colorSecondary: "#EAB308",
    category: "multimodal",
    websiteUrl: "https://notebooklm.google.com",
    blogUrl: null,
  },
];

// AI Model category filter tabs
export const AI_MODEL_CATEGORIES = [
  { value: "all", label: "All" },
  { value: "llm", label: "LLM" },
  { value: "image", label: "Image" },
  { value: "code", label: "Code" },
  { value: "search", label: "Search" },
  { value: "multimodal", label: "Multi" },
  { value: "open-source", label: "Open" },
] as const;
